[[main]]
  url = "/pubs"
  name = "Publications"
  weight = 1


[[main]]
  name = "About"
  identifier = "about"
  url = ""
  weight = "5"


[[main]]
  name = "Team"
  identifier = "team"
  url = "/team/"
  weight = "501"
  parent = "about"

[[main]]
  name = "DAPPER"
  identifier = "dapper"
  url = "/about/"
  weight = "502"
  parent = "about"



[[main_right]]
  url = "/contact/"
  name = "<i class='far fa-envelope' style='color:#333'></i>"
  identifier = "mail"
  weight = 1

[[main_right]]
  url = "https://www.github.com/dapperstats/dapperpub"
  name = "<i class='fab fa-github-alt' style='color:#333'></i>"
  identifier = "github"
  weight = 2

[[main_right]]
  url = "https://www.twitter.com/dapperpub"
  name = "<i class='fab fa-twitter' style='color:#55acee'></i>"
  identifier = "twitter"
  weight = 3